version: '3.8'

services:
  db:
    image: postgres:15    # Usando la versión 15 de PostgreSQL
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root       # Usuario de la base de datos
      POSTGRES_PASSWORD: root   # Contraseña del usuario
      POSTGRES_DB: mydatabase    # Nombre de la base de datos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "3005:5432"  # Exponer el puerto 5432 para acceder a PostgreSQL desde el host

volumes:
  postgres_data:
    driver: local
